spring:
  application:
    name: vole-sso
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: vole-config-server
        enabled: true
      profile: ${spring.profiles.active}

---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:1025/eureka/

#logging:
#  level:
#    org.springframework: debug

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1025/eureka/